name: Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    types: labeled
jobs:
  label:
    name: Find 'Test Matoya' Label
    runs-on: ubuntu-latest
    outputs:
      label_exists: ${{contains(steps.pull_request.outputs.result, 'Test Matoya') || contains(toJson(github.event.label.name), 'Test Matoya')}}
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    steps:
      - name: pull_request
        id: pull_request
        uses: actions/github-script@v7
        with:
          script: |
            pull_requests = (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })).data;
            if (pull_requests.constructor === Array && pull_requests.length > 0 && "labels" in pull_requests[0])
                return pull_requests[0]["labels"];
            return "";
  macos:
    name: macOS
    runs-on: macos-latest
    needs: label
    if: ${{needs.label.outputs.label_exists == 'true'}}
    permissions:
      id-token: write
      contents: read
    env:
      TERM: xterm-256color
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          path: libmatoya
      - name: Test
        run: |
          cd libmatoya
          make ARCH=arm64
          cd test
          make ARCH=arm64
  linux:
    name: Linux
    runs-on: ubuntu-latest
    needs: label
    if: ${{needs.label.outputs.label_exists == 'true'}}
    permissions:
      id-token: write
      contents: read
    env:
      TERM: xterm-256color
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          path: libmatoya
      - name: Test
        run: |
          cd libmatoya
          make
          cd test
          make
  windows:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    needs: label
    if: ${{needs.label.outputs.label_exists == 'true'}}
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Windows x64", os: windows-2022, bits: 64 }
    env:
      VCVARS_PATH: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          path: libmatoya
      - name: Test
        shell: cmd
        run: |
          call "%VCVARS_PATH%/vcvars${{ matrix.config.bits }}.bat"
          cd libmatoya
          nmake
          cd test
          nmake
